import os
while 1:
    os.system("clear")
    os.system("tput setaf 9")
    print("\t\t\tLogical Volume Automation\n")
    os.system("tput setaf 3")
    print("""\t\tPress 1 : Create a Logical Volume\n\t\tPress 2 : Extend the size of Logical Volume\n\t\tPress 3 : Reduce the size of Logical Volume\n\n\t\tPress e : to exit\n""")
    os.system("tput setaf 2")
    choice=input("Enter your choice : ")
    l=[]
    os.system("tput setaf 7")
    if choice=='1' :
        choice1=input("Do you want to create Logical Volume from Physical Volume or Volume Group? (pv/vg) : ")
        if choice1=='pv':
            n=int(input("Enter the number of physical volumes to create : "))
            print("\n")
            for i in range(n):
                l.append(input("Enter the name of hard disk{} (Ex: /dev/sdc): ".format(i+1)))
            for i in range(n):
                os.system("pvcreate {}".format(l[i]))
            print("\n")
            vgname=input("Enter the name of Volume Group : ")
            s=" ".join(l)
            os.system("vgcreate {} {}".format(vgname,s))
            print("\n")
            size=input("Enter the size of Logical Volume (Ex: 50G,5G...): ")
            lvname=input("Enter the name of Logical Volume : ")
            os.system("lvcreate --size {} --name {} {}".format(size,lvname,vgname))
            print("\n")
            os.system("mkfs.ext4 /dev/{}/{}".format(vgname,lvname))
            print("\n")
            directory=input("Enter the path to mount the Logical Volume (Ex: /root/dir) : ")
            os.system("mkdir {}".format(directory))
            os.system("mount /dev/{}/{} {}".format(vgname,lvname,directory))
            print("\n")
        elif choice1=='vg':
            vgname=input("Enter the name of the Volume Group : ")
            size=input("Enter the size of the Logical Volume : ")
            lvname=input("Enter the name of the Logical Volume : ")
            print("\n")
            os.system("lvcreate --size {} --name {} {}".format(size,lvname,vgname))
            print("\n")
            os.system("mkfs.ext4 /dev/{}/{}".format(vgname,lvname))
            directory=input("Enter the path to mount the Logical Volume (Ex: /root/dir) : ")
            os.system("mkdir {}".format(directory))
            os.system("mount /dev/{}/{} {}".format(vgname,lvname,directory))
    elif choice=='2':
        size=input("Enter the size to extend the Logical Volume (Ex: +5G,+3G...): ")
        vgname=input("Enter the Volume Group Name : ")
        lvname=input("Enter the Logical Volume Name : ")
        print("\n")
        os.system("lvextend --size {} /dev/{}/{}".format(size,vgname,lvname))
        print("\n")
        os.system("resize2fs /dev/{}/{}".format(vgname,lvname))
    elif choice=='3':
        path=input("Enter the path of Directory where the Logical Volume is mounted (Ex: /root/dir) : \n")
        os.system("umount {}".format(path))
        vgname=input("Enter the Volume Group Name : ")
        lvname=input("Enter the Logical Volume Name : ")
        print("\n")
        os.system("e2fsck -f /dev/{}/{}".format(vgname,lvname))
        print("\n")
        size=input("Enter the new size of Logical Volume (Ex: 10G,3G...) : ")
        print("\n")
        os.system("resize2fs /dev/{}/{} {}".format(vgname,lvname,size))
        print("\n")
        os.system("lvreduce --size {} /dev/{}/{}".format(size,vgname,lvname))
        print("\n")
        os.system("mount /dev/{}/{} {}".format(vgname,lvname,path))
    elif choice=='e':
        os.system("tput reset")
        exit()
    print("\n====================================================================\n")
    input("Press Enter to continue...........")
